from typing import Protocol

from app.domain.models import Meeting


class MeetingRepository(Protocol):
    def add(self, meeting: Meeting) -> Meeting: ...

    def list(self) -> list[Meeting]: ...

    def get(self, meeting_id: str) -> Meeting | None: ...

    def update(self, meeting: Meeting) -> Meeting | None: ...

    def delete(self, meeting_id: str) -> Meeting | None: ...
